### ISSUE TITLE
Chip my be OTP & bootup EEPROM traffic

### ISSUE THREAD

**Issue by usedbytes** [yeokm1/ndp2019-wristband-teardown#1]
Hi, I got my hands on a couple of these earlier in the year. Mine are version:
```
PALM v1.7
20181219
0919
```
I don't think it can be the MC81F4104, as you have pointed out the VSS/VDD pins are reversed.

I agree the chip is probably ABOV, my main reason being the funny chamfer on the edge of the package: https://twitter.com/PixMobOfficial/status/1138151577989058567

In that tweet thread, they said "there isn't a hack possible", which reinforces my thought: I wondered if it might be one of the one-time-programmable parts, like the ADAM46P20XX, which has the supply pins in the right place (though that isn't much to go on). And they didn't reply to me :-(
https://www.abov.co.kr/en/index.php?Depth1=3&Depth2=1&Depth3=1&Depth4=3&Item=ADAM46P2008

I captured the traffic between the main chip and the EEPROM at power-on, it wasn't very enlightening (it's definitely not reading code from the EEPROM):

```
i2c-1: Start
i2c-1: Read
i2c-1: Address read: 7F
i2c-1: ACK
i2c-1: Stop
i2c-1: Start
i2c-1: Write
i2c-1: Address write: 50
i2c-1: ACK
i2c-1: Data write: 03
i2c-1: ACK
i2c-1: Start repeat
i2c-1: Read
i2c-1: Address read: 50
i2c-1: ACK
i2c-1: Data read: F3
i2c-1: NACK
i2c-1: Stop
i2c-1: Start
i2c-1: Write
i2c-1: Address write: 50
i2c-1: ACK
i2c-1: Data write: 00
i2c-1: ACK
i2c-1: Start repeat
i2c-1: Read
i2c-1: Address read: 50
i2c-1: ACK
i2c-1: Data read: 05
i2c-1: NACK
i2c-1: Stop
i2c-1: Start
i2c-1: Write
i2c-1: Address write: 50
i2c-1: ACK
i2c-1: Data write: 01
i2c-1: ACK
i2c-1: Start repeat
i2c-1: Read
i2c-1: Address read: 50
i2c-1: ACK
i2c-1: Data read: 00
i2c-1: NACK
i2c-1: Stop
i2c-1: Start
i2c-1: Write
i2c-1: Address write: 50
i2c-1: ACK
i2c-1: Data write: 02
i2c-1: ACK
i2c-1: Start repeat
i2c-1: Read
i2c-1: Address read: 50
i2c-1: ACK
i2c-1: Data read: 00
i2c-1: NACK
i2c-1: Stop
i2c-1: Start
i2c-1: Write
i2c-1: Address write: 50
i2c-1: ACK
i2c-1: Data write: 08
i2c-1: ACK
i2c-1: Start repeat
i2c-1: Read
i2c-1: Address read: 50
i2c-1: ACK
i2c-1: Data read: 01
i2c-1: NACK
i2c-1: Stop
```
I kinda fancied trying to fuzz the IR but I lost interest

**Comment by yeokm1** [comment]
Hi @usedbytes!

Thanks for the effort. I'm no longer working on this project but I do hope your capture traffic will be useful to somebody.
